devCenterUserIdentity = "dev-poc-uid-aue-001"
devCenterName         = "dev-poc-dc-aue-001"
projectName           = "dev-poc-prj-aue-001"
galleryName           = "devpocglraue001"
imageDefinitionName   = "dev-poc-imgdef-aue-001"
imageTemplateName     = "dev-poc-imgtemp-aue-001"
devBoxPoolName        = "dev-poc-dbp-aue-001"